services:
  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOSTNAME=${HOSTNAME:-unknown}
    volumes:
      - /var/log/app:/var/log/app:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - ./positions:/var/lib/promtail
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
