server:
  http_listen_port: 9080

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://${LOKI_HOST}:3100/loki/api/v1/push
    batchwait: 1s
    batchsize: 102400
    timeout: 10s


scrape_configs:
  # Spring Boot Backend
  - job_name: billages-backend
    static_configs:
      - targets: [localhost]
        labels:
          job: billages-backend
          env: ${ENV}
          __path__: ${SPRING_LOG_FILE_PATH}
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}T'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z)\s+(?P<level>INFO|WARN|ERROR|DEBUG)\s+(?P<pid>\d+)\s+---\s+\[(?P<thread>[^\]]+)\]'
      - timestamp:
          source: timestamp
          format: '2006-01-02T15:04:05.000Z'
      - labels:
          level:
          thread:

  # Nginx
  - job_name: nginx
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          env: ${ENV}
          __path__: ${NGINX_LOG_FILE_PATH}
    pipeline_stages:
      - regex:
          expression: '" (?P<status>\d+) '
      - labels:
          status:
